basePath: /api/v1
definitions:
  domain.Response:
    properties:
      data:
        type: object
      success:
        type: boolean
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a Test.
  title: Swagger Example API
  version: "1.0"
paths:
  /persons/suggestions:
    get:
      parameters:
      - description: Строка адреса
        in: query
        name: query
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.Response'
      summary: Get All Suggestions of specified query
      tags:
      - Persons
swagger: "2.0"
